### PR TITLE
Changes allow VACCA to run with Taurus 4 but keeps backward compatibility with Taurus 3

### PR DESCRIPTION
**Pull request by MikeFalowski**
Tree widget is not working. PANIC cannot be present. Not tested with PyTangoArchiving

### CODE REVIEW

**Comment by sergirubio** [comment]
Hi, great news!, I'm just validating the patch locally on my test bench and I'll proceed today with the merge.

Many thanks!

Sergi

**Comment by sergirubio** [comment]
Hi Mike, it's almost finish; but I had to do a patch in Taurus due to some bugs in taurus:

https://github.com/taurus-org/taurus/pull/402

If you want to continue testing vacca I advice to temporarily use my fork at sergirubio/taurus until the fix will be applied to taurus/develop

**Comment by sergirubio** [comment]
Merged done (with some extra patches) into taurus4 branch; I'll merge it into develop once the fixes needed will be available in taurus. Until then use it with sergirubio/taurus fork.

**Comment by MikeFalowski** [comment]
Thank you very much for upgrades Sergi.

I will use your fork of Taurus then, hopefully there will be no additional problems. 
Maybe I’ll look also into PANIC why is it not loading.

**Comment by sergirubio** [comment]
Well, C.Pascual just merged the changes into taurus-org/develop so you don't need to use my fork.

I have several modifications ongoing in the Panic widgets so better wait 'til I commit my work before doing any changes.

**Pull request merged**
